# Generated by Django 4.2.1 on 2024-01-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0008_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
