# Generated by Django 4.2.1 on 2024-02-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0010_manufacturer_remove_product_vendor_delete_vendor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
