# Generated by Django 4.2.1 on 2024-02-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0011_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
