# Generated by Django 4.2.1 on 2024-02-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0012_remove_product_digital_remove_product_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': 'Order Items'},
        ),
    ]
