# Generated by Django 4.2.1 on 2024-03-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0014_alter_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
