# Generated by Django 4.2.1 on 2024-03-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0017_cartorder_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='address',
            new_name='delivery_address',
        ),
    ]
