# Generated by Django 4.2.1 on 2024-03-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0018_rename_address_cartorder_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
