# Generated by Django 5.0.3 on 2024-03-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0020_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice No.'),
        ),
    ]
