# Generated by Django 5.0.3 on 2024-03-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCS_APP', '0021_alter_cartorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='invoice_no',
            field=models.IntegerField(verbose_name='Invoice No.'),
        ),
    ]
